# Generated by Django 2.1.8 on 2019-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('cpu', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20, null=True)),
                ('sn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ostype', models.CharField(max_length=20)),
                ('ports', models.CharField(max_length=10, null=True)),
                ('application', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default='1')),
            ],
        ),
    ]
